<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="diplomaticpulse.tests.test_get_date_from_pdf.TestParsingdates-20220209183818" skipped="0" tests="4" time="0.003" timestamp="2022-02-09T18:38:20">
	<testcase classname="diplomaticpulse.tests.test_get_date_from_pdf.TestParsingdates" name="test_get_date_from_pdf1" time="0.000" timestamp="2022-02-09T18:38:20"/>
	<testcase classname="diplomaticpulse.tests.test_get_date_from_pdf.TestParsingdates" name="test_get_date_from_pdf3" time="0.003" timestamp="2022-02-09T18:38:20"/>
	<testcase classname="diplomaticpulse.tests.test_get_date_from_pdf.TestParsingdates" name="test_get_date_from_pdf4" time="0.000" timestamp="2022-02-09T18:38:20"/>
	<testcase classname="diplomaticpulse.tests.test_get_date_from_pdf.TestParsingdates" name="test_get_date_from_pdf2" time="0.000" timestamp="2022-02-09T18:38:20">
		<failure message="'2022-02-09' != '2021-09-04'
- 2022-02-09
+ 2021-09-04
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/alattab/projects/docker/DiplomaticPulse/diplomaticpulse/tests/test_get_date_from_pdf.py", line 39, in test_get_date_from_pdf2
    self.assertEqual(expected, result)
AssertionError: '2022-02-09' != '2021-09-04'
- 2022-02-09
+ 2021-09-04

]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
