<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" name="diplomaticpulse.tests.test_parse_mydate.TestParsingdates-20220209183818" skipped="0" tests="2" time="0.037" timestamp="2022-02-09T18:38:25">
	<testcase classname="diplomaticpulse.tests.test_parse_mydate.TestParsingdates" name="test_parse_mydate1" time="0.000" timestamp="2022-02-09T18:38:25"/>
	<testcase classname="diplomaticpulse.tests.test_parse_mydate.TestParsingdates" name="test_parse_mydate2" time="0.036" timestamp="2022-02-09T18:38:25"/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[/home/alattab/envs/docker/lib/python3.6/site-packages/dateparser/date_parser.py:35: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  date_obj = stz.localize(date_obj)
]]>	</system-err>
</testsuite>
